name: Develop - build and push image
on:
  push:
    branches:
      - master
env:
  ENVIRONMENT: develop

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish
    runs-on: [ self-hosted ]
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NX workspace SHAs
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Dependencies
        run: yarn

      - name: Login to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH }}" >> .npmrc

      - name: Compute actually changed files
        run: |
          git config user.email "ci@ci.com"
          git config user.name "CI"
          git cherry-pick --abort || true
          export NX_CURRENT_BRANCH=`git branch --show-current`
          git checkout $NX_BASE
          git cherry-pick `git log  $NX_BASE..$NX_HEAD --grep='\[skip ci\]' --invert-grep  --no-merges  --pretty="%H" | tr '\n' ' '` || true
          NX_AFFECTED_FILES=`git diff $NX_BASE --name-only | sort | uniq | tr '\n' ','`
          NX_AFFECTED_FILES=`echo "${NX_AFFECTED_FILES%?}"`
          git cherry-pick --abort || true
          git checkout $NX_CURRENT_BRANCH
          echo "NX_HEAD=''" >> $GITHUB_ENV
          echo "NX_AFFECTED_FILES=$NX_AFFECTED_FILES" >> $GITHUB_ENV
          echo "Affected files: $NX_AFFECTED_FILES"
      - name: 'Build affected apps'
        run:  yarn nx affected --target=ci --parallel=1 --files="$NX_AFFECTED_FILES" --base-commit="$NX_BASE"
